"""GitLab system wide Constants"""
PROJECT_PATH_KEY = "project_path"
PROJECT_ENV_KEY = "environment"
GITLAB_CONFIG_KEY = "gitlab"
GITLAB_URL_KEY = "url"
GITLAB_ENDPOINT_KEY = "endpoint"
GITLAB_TOKEN_KEY = "token"
